version: '2'

services:
  web:
    image: prestashop/prestashop:1.6-7.0
    container_name: prestashop
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - ${PWD}/volumes/prestashop:/var/www/html
    depends_on:
      - mysql 
    environment:
      - DB_SERVER=mysql
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ${PWD}/volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
